version: '3'

services:
  db:
    image: mongo
    env_file: 
      - ./base.env
  api:
    image: patricksison/docker-node-react
    command: bash -c "cd /app && nodemon index.js"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./base.env
    ports:
      - "8080:8080"
